<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    // Fields that can be mass assigned
    protected $fillable = ['title', 'excerpt', 'body', 'slug'];

    // Fields that cannot be mass assigned
    protected $guarded = ['id'];

    // Dates that may be formatted to be human readable
    protected $dates = ['created_at'];

    // Relationships that'd always be auto-loaded
    // protected $with = ['author', 'category'];

    public function scopeFilter($query, array $filters)
    {
        if ($filters['search'] ?? false) {
            $query
                ->where('title', 'like', '%' . $filters['search'] . '%')
                ->orWhere('body', 'like', '%' . $filters['search'] . '%');
        }
    }

    public function author() {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    // Changes the key to be used to find when using route model binding
//    public function getRouteKeyName()
//    {
//        return 'slug'; // TODO: Change the autogenerated stub
//    }
}
